# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_widget(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(563, 607)
        self.label = QtWidgets.QLabel(widget)
        self.label.setGeometry(QtCore.QRect(160, 20, 121, 41))
        self.label.setObjectName("label")
        self.groupBox = QtWidgets.QGroupBox(widget)
        self.groupBox.setGeometry(QtCore.QRect(30, 100, 121, 171))
        self.groupBox.setObjectName("groupBox")
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 60, 91, 21))
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 90, 91, 21))
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_7 = QtWidgets.QPushButton(self.groupBox)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 120, 91, 21))
        self.pushButton_7.setObjectName("pushButton_7")
        self.groupBox_2 = QtWidgets.QGroupBox(widget)
        self.groupBox_2.setGeometry(QtCore.QRect(190, 100, 131, 171))
        self.groupBox_2.setObjectName("groupBox_2")
        self.pushButton_4 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 30, 91, 21))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_8 = QtWidgets.QPushButton(self.groupBox_2)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 60, 91, 21))
        self.pushButton_8.setObjectName("pushButton_8")
        self.groupBox_3 = QtWidgets.QGroupBox(widget)
        self.groupBox_3.setGeometry(QtCore.QRect(350, 100, 151, 171))
        self.groupBox_3.setObjectName("groupBox_3")
        self.pushButton_5 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 20, 111, 21))
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 50, 111, 21))
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_9 = QtWidgets.QPushButton(self.groupBox_3)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 80, 111, 21))
        self.pushButton_9.setObjectName("pushButton_9")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(widget)
        self.plainTextEdit.setGeometry(QtCore.QRect(30, 300, 471, 131))
        self.plainTextEdit.setObjectName("plainTextEdit")

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "Form"))
        self.label.setText(_translate("widget", "AWS云上管理系统"))
        self.groupBox.setTitle(_translate("widget", "S3"))
        self.pushButton.setText(_translate("widget", "存储桶List"))
        self.pushButton_2.setText(_translate("widget", "查询数据"))
        self.pushButton_3.setText(_translate("widget", "上传数据"))
        self.pushButton_7.setText(_translate("widget", "删除数据"))
        self.groupBox_2.setTitle(_translate("widget", "Snowball"))
        self.pushButton_4.setText(_translate("widget", "SnowballList"))
        self.pushButton_8.setText(_translate("widget", "查询状态"))
        self.groupBox_3.setTitle(_translate("widget", "EC2"))
        self.pushButton_5.setText(_translate("widget", "数据查询"))
        self.pushButton_6.setText(_translate("widget", "数据传输"))
        self.pushButton_9.setText(_translate("widget", "数据删除"))
